### ISSUE TITLE
Deploy with Heroku

### ISSUE THREAD

**Issue by FRosner** [Bantolomeus/ChitChat#10]
- https://www.heroku.com/java
- We might need to add yarn to the package lifecycle (https://gist.github.com/phillipgreenii/7c954e3c3911e5c32bd0#file-pom-xml-L31 or https://github.com/eirslett/frontend-maven-plugin)

**Comment by Bantolomeus** [comment]
@FRosner I was looking into configuring the Procfile, but I am stuck, maybe you can help me out?

**Comment by Bantolomeus** [comment]
YIS, it works great. At least for desktop

**Comment by FRosner** [comment]
> YIS, it works great. At least for desktop

wat?

**Comment by Bantolomeus** [comment]
did you not say:"It is not scalable" and then we saw a screenshot with only a part of posted picture. It is nice for Desktop web and not mobile web?

**Comment by FRosner** [comment]
I see what you mean. How does it relate to the Heroku deployment?

**Comment by Bantolomeus** [comment]
Well, you are right. I will take "At least for desktop" back
