### ISSUE TITLE
Use Travis

### ISSUE THREAD

**Issue by FRosner** [Bantolomeus/ChitChat#17]
- [x] set up chitchat in travis
- [x] integrate build status in readme
- [x] fix travis build
- [x] `mvn package`
- [x] integration with heroku so heroku app gets deployed and updated when travis build is green
- [x] resolve issue till 5.9. 23:59
- [x] deploy only on master pushes

**Comment by Bantolomeus** [comment]
Help for Travis to build our stuff https://github.com/elm-community/elm-test/issues/42

**Comment by FRosner** [comment]
https://travis-ci.org/Bantolomeus/ChitChat/builds/270539187

**Comment by Bantolomeus** [comment]
have to solve access right problem to install travis

**Comment by Bantolomeus** [comment]
*cough* sudo solved the problem

**Comment by Bantolomeus** [comment]
/*cough/* sudo solved the problem

**Comment by Bantolomeus** [comment]
sudo solved the problem

**Comment by FRosner** [comment]
Can you be \*more\* specific on what was the problem? :)

**Comment by Bantolomeus** [comment]
Build is broken again. https://travis-ci.org/Bantolomeus/ChitChat/builds/272164322 

I just added 
`deploy:
  provider: heroku
  api_key:
    secure: ApiKey
  app: cryptic-fjord-48959
  on:
repo: Bantolomeus/ChitChat`

**Comment by Bantolomeus** [comment]
Fixed. Thx @FRosner
