### ISSUE TITLE
Lost first message on heroku server

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/ChitChat#19]
If heroku is in sleep mode (after x minutes) and someone sends a message in the chat application, heroku wakes up and the message should be visible in the chat, but it is lost.

- [ ] find out how sleep mode of heroku works and what exactly it is
- [ ] find out how to debug heroku
- [ ] find the problem/bug and fix it
- [ ] will cache disabling solve this behavior?
optional: 
- [ ] debug local (bug may not reproducible local)

**Comment by FRosner** [comment]
How do you know if Heroku is in sleep mode? What is the sleep mode? How come you can go to the website and see the frontend if it is in sleep mode? Does it also happen when caching the HTML files is disabled?

**Comment by FRosner** [comment]
I just tried it today and the sleeping is showing itself by going to the page and the initial load taking some time (probably because the application gets started lazily). After it started I didn't lose any messages, though. Can you post steps to reproduce the issue? Are you able to reproduce it?

**Comment by Bantolomeus** [comment]
I will try it out

**Comment by Bantolomeus** [comment]
Closed because I can not reproduce the described behavior. 
On second though, yesterday we had network problems, it was most likely the network problems fault.
